
--

CREATE TABLE IF NOT EXISTS xxxxxx (

    xxxxxxId    INT(10) UNSIGNED    NOT NULL AUTO_INCREMENT

,	createdOn   DATETIME 		    DEFAULT CURRENT_TIMESTAMP
,	updatedOn   DATETIME 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

,   PRIMARY KEY (activeId)
);

